# Generated by Django 4.2.1 on 2024-04-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_post_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.IntegerField(default=2020),
        ),
    ]
